load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

py_proto_library(
    name = "op_g_counter_proto_py",
    srcs = ["op_g_counter.proto"],
)
