load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "u_set_proto",
    srcs = ["u_set.proto"],
)

py_proto_library(
    name = "u_set_proto_py",
    srcs = ["u_set.proto"],
)
