load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "counter_proto",
    srcs = ["counter.proto"],
)

py_proto_library(
    name = "counter_proto_py",
    srcs = ["counter.proto"],
)
